### ISSUE TITLE
Request that provide additional Environments settings for the API URL, allowing the replacement of the base URL "https://api.openai.com" with an alternative proxy URL?

### ISSUE THREAD

**Issue by Alano-i** [AirCodeLabs/documate#43]
### Describe the bug

I am using the api url of the proxy, because there is no place to set the request url address, so I keep getting errors.

Request that provide additional Environments settings for the API URL, allowing the replacement of the base URL "https://api.openai.com" with an alternative proxy URL.

Thanks.

**Comment by adcentury** [comment]
Since adding a proxy is not the usual way for integration, we will not provide official support. However, you can modify the backend code of your own App to achieve that.
