### ISSUE TITLE
upload success but search old markdown contents

### ISSUE THREAD

**Issue by bianbiandashen** [AirCodeLabs/documate#47]
### What operating system are you using?

Mac

### Describe the bug

![image](https://github.com/AirCodeLabs/documate/assets/16240681/aadfd63f-a46d-443c-b1d3-a8e0cd0af05a)
![image](https://github.com/AirCodeLabs/documate/assets/16240681/1e92eceb-21cf-4614-9a77-e1f1b20c842e)

### Steps to reproduce

![image](https://github.com/AirCodeLabs/documate/assets/16240681/22f15b22-896f-4411-9752-536911554009)

**Comment by akira-cn** [comment]
@bianbiandashen fixed now. 

Please sync and redeploy your backend.

Thanks to report.
