### ISSUE TITLE
Error: No NavbarItem component found for type "custom-documate".

### ISSUE THREAD

**Issue by snowinszu** [AirCodeLabs/documate#49]
### What operating system are you using?

Mac

### Describe the bug

When run build for docusaurus project, it shows error:
Error: No NavbarItem component found for type "custom-documate".

### Steps to reproduce

npm run build

**Comment by akira-cn** [comment]
Hi，I updated the docusaurus project template. Could you please create a new project to test it again? I couldn't fully reproduce your issue, but I suspect it should be working fine now. If there are any problems, please provide us with feedback. Thank you very much.
