### ISSUE TITLE
Ask some questions

### ISSUE THREAD

**Issue by daydayfish** [AirCodeLabs/documate#52]
### What operating system are you using?

Mac

### Describe the bug

Does Documate support incremental updates for document uploads?
Where did the uploaded documents go in Documate?
Is Documate tightly integrated with the airCode platform? Does it support deployment on other platforms?

Documate 上传文档支持增量更新吗？
Documate 上传文档放到哪里去了？
Documate 和airCode平台强绑定吗？支持其他平台的部署？

### Steps to reproduce

-

**Comment by 0xinhua** [comment]
@daydayfish 是支持增量更新的，上传的文档目前存放在你 copy 创建的 AirCode 应用数据库里，目前后端接口部署在 AirCode 上，暂不支持其它平台，欢迎贡献 pr。
